### PR TITLE
fix error handling

### LINKED ISSUE #1: Fix improper error handling
https://github.com/robertkowalski/get-license-npm/blob/master/lib/index.js#L31

https://github.com/robertkowalski/get-license-npm/blob/master/lib/index.js#L66

By throwing inside of those async functions (instead of rejecting the promise or executing the callback early with the error parameter) you are basically crushing the Node process without giving the user the possibility to handle the error.

### PR DESCRIPTION
**Pull request by alessioalex**
closes #1

### CODE REVIEW

File: lib/index.js [hunk 1]
```diff
@@ -20,15 +22,30 @@ const LICENSES = [
...
+
 module.exports = getLicense
 function getLicense (modulePath, optionalCallback) {
+  const cb = optionalCallback || noop
+
   return new Promise((resolve, reject) => {
-    const pkg = require(path.join(modulePath, 'package.json'))
+    let pkg = {}
+
+    try {
```
Comment (alessioalex) [inline lib/index.js]: This is done in order to forward the error with the callback interface as well. If we don't do this the callback will never get executed when the user typed in the wrong module path.

File: lib/index.js [hunk 2]
```diff
@@ -20,15 +22,30 @@ const LICENSES = [
   'licence.md'
 ]
 
+const noop = () => {}
+
 module.exports = getLicense
 function getLicense (modulePath, optionalCallback) {
+  const cb = optionalCallback || noop
```
Comment (alessioalex) [inline lib/index.js]: Instead of `if-else` checks everywhere we can just default to `noop` and use that all over the place for the callback interface.

File: lib/index.js [hunk 3]
```diff
@@ -63,7 +77,7 @@ function makeTask (modulePath, file) {
     const where = path.join(modulePath, file)
     fs.stat(where, (err, stats) => {
       if (err && err.code === 'ENOENT') return cb(null, false)
-      if (err) throw err
```
Comment (alessioalex) [inline lib/index.js]: As discussed in the ticket, throwing inside of an async function won't make the Promise forward the error so that the user can use `catch()`. We also need to be vary of not throwing since we support a callback api as well (and that won't get automatically called as promises do because of their implicit try-catch).

**Comment by robertkowalski** [comment]
tests are failing

**Comment by alessioalex** [comment]
@robertkowalski the tests are failing because they cannot find the `async` module (`Error: Cannot find module 'async/waterfall'`). This was fixed in another pull request.

**Comment by robertkowalski** [comment]
awesome, you can publish now :)

On Thu, Sep 29, 2016 at 3:52 PM, Alexandru Vlăduţu <notifications@github.com

**Comment by robertkowalski** [comment]
restarted travis, looks good, +1
